In [14]:
import numpy as np

a=np.array([1,2,3,4,5])

print(f"The elements is the array are {a}")
print(f"The sum of the array is {np.sum(a)}")
print(f"The mean of the array is {np.mean(a)}")
new_array=np.array([x*2 for x in a])
print(f"The new array is{new_array}")

The elements is the array are [1 2 3 4 5]
The sum of the array is 15
The mean of the array is 3.0
The new array is[ 2  4  6  8 10]


In [21]:
import numpy as np

a=np.array([[1,2],[5,6]])
b=np.array([[8,7],[4,3]])
c=np.dot(a,b)
print(f"{a} X\n {b} =\n{c}")

# for i in range(2):
#     for j in range(2):
#         for k in range(2):
#             c[i][j]=a[i][]*b[]


[[1 2]
 [5 6]] X
 [[8 7]
 [4 3]] =
[[16 13]
 [64 53]]


In [23]:
from collections import deque

a=deque([])

while True:
    print("""Choices 
    1. Add task
    2. Remove Task
    3. Postpone Task
    4. Break""")
    x=int(input("Enter a choice(1/2/3)"))
    if x==1:
        y=input("Enter the task")
        a.append(y)
    elif x==2:
        a.popleft()
        print("Task removed")
    elif x==3:
        z=a.popleft()
        a.append(z)
        print("Task postponed")
    elif x==4:
        break
    else:
        print("Wrong choice")
print(a)

Choices 
    1. Add task
    2. Remove Task
    3. Postpone Task
    4. Break
Enter a choice(1/2/3)1
Enter the taskrun
Choices 
    1. Add task
    2. Remove Task
    3. Postpone Task
    4. Break
Enter a choice(1/2/3)1
Enter the taskhomework
Choices 
    1. Add task
    2. Remove Task
    3. Postpone Task
    4. Break
Enter a choice(1/2/3)1
Enter the taskcoo
Choices 
    1. Add task
    2. Remove Task
    3. Postpone Task
    4. Break
Enter a choice(1/2/3)1
Enter the taskcook
Choices 
    1. Add task
    2. Remove Task
    3. Postpone Task
    4. Break
Enter a choice(1/2/3)2
Task removed
Choices 
    1. Add task
    2. Remove Task
    3. Postpone Task
    4. Break
Enter a choice(1/2/3)3
Task postponed
Choices 
    1. Add task
    2. Remove Task
    3. Postpone Task
    4. Break
Enter a choice(1/2/3)4
deque(['coo', 'cook', 'homework'])


In [39]:
from collections import Counter

a="""The moonlight dances on the calm ocean waves, casting shadows on the shore .  
Whispers of the wind carry secrets that only the stars can hear the ocean ."""

a=a.lower().split()
words=Counter(a)

print("Word Frequency:")
for word, count in words.most_common(3):
    print(f"{word}: {count}")


Word Frequency:
the: 6
on: 2
ocean: 2


In [ ]:
from collections import defaultdict

x=defaultdict(list)

while True:
    print("""Choices 
    1. Fruits
    2. Vegetable
    3. Dairy
    4. Break""")
    z=int(input("Enter a choice(1/2/3)"))
    if z==1:
        y=input("Enter the fruit")
        x["Fruits"].append(y)
    elif z==2:
        y=input("Enter the vegetable") 
        x["Vegetable"].append(y)
    elif z==3:
        y=input("Enter the dairy")
        x["Dairy"].append(y)
    elif z==4:
        break
    else:
        print("Wrong choice")
print(x)

Choices 
    1. Fruits
    2. Vegetable
    3. Dairy
    4. Break


In [ ]:
import csv

file_path="data.csv"

