In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print("1D array")
print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np
ar=np.array([[1,2,3],[4,5,6]])
print("2D array")
print(ar)

2D array
[[1 2 3]
 [4 5 6]]


In [7]:
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(d)

0
1
2
3
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [9]:
print(c[0,1])
print(d[0,0,2])

2
3


In [4]:
import numpy as np
import random 

matrix= np.random.randint(1,21,(4,4))
print("Original Matrix")
print(matrix)

diagonal_sum=np.trace(matrix)
print(f"\n Sum of diagonal elements:{diagonal_sum}")

flipped_matrix=np.flip(matrix)
print("\n Flipped matrix:")
print(flipped_matrix)

positions=np.argwhere(matrix>15)
print("\n Positons of elements greater than 15:")
for pos in positions:
    print(f"Row {pos[0]+1},Column {pos[1]+1}")

Original Matrix
[[ 9  3  6 14]
 [20  9 14 13]
 [ 1 11 20  7]
 [12  6  9  9]]

 Sum of diagonal elements:47

 Flipped matrix:
[[ 9  9  6 12]
 [ 7 20 11  1]
 [13 14  9 20]
 [14  6  3  9]]

 Positons of elements greater than 15:
Row 2,Column 1
Row 3,Column 3


In [6]:
import csv

file_path="sales_tracker.csv"

def create_csv():
    headers=["Date","Product","Quantity","Price per Unit","Total"]
    with open(file_path,mode='w',newline="") as file:
        writer=csv.writer(file)
        writer.writerow(headers)
    print("Sales tracker created.")
    
def add_sale(date,product,quantity,price_per_unit):
    total=quantity*price_per_unit
    with open(file_path,mode="a",newline="") as file:
        writer=csv.writer(file)
        writer.writerow([date,product,quantity,price_per_unit,total])
    print("Sale record added.")
    
def calculate_total_sales():
    total_sales=0
    with open(file_path,mode="r") as file:
        reader=csv.DictReader(file)
        for row in reader:
            total_sales+=float(row["Total"])
    print(f"Total Sales: ${total_sales:.2f}")
    
create_csv()
add_sale("2025-01-06","Laptop",2,1200.50)
add_sale("2025-01-06","Mouse",5,25.99)
calculate_total_sales()

Sales tracker created.
Sale record added.
Sale record added.
Total Sales: $2530.95


In [50]:
import csv
import numpy as np
import random

file_path1="sales_data.csv"
file_path2="sales_summary.csv"

def create_sd():
    headers=["Product","Region","Sales","Price"]
    with open(file_path1,mode="w",newline="") as file:
        writer=csv.writer(file)
        writer.writerow(headers)
    print("Sales Data created.")
    
def add_sale(product,region,sales,price):
    with open(file_path1,mode="a",newline="")as file:
        writer=csv.writer(file)
        writer.writerow([product,region,sales,price])
    print("Sale Record added")

def generate_random_sales_data(num_record):
    products=["Laptop","Samartphone","Tablet","Headphones","Mouse"]
    regions=["Kathmandu","Pokhara","Birgunj","Illam"]
    
    for _ in range(num_record):
        product=random.choice(products)
        region=random.choice(regions)
        sales=random.randint(10,500)
        price=round(random.uniform(10.0,2000.0),2)
        add_sale(product,region,sales,price)
    print(f"Generated {num_record} random sales records.")
    
def create_ss():
    headers=["Product","Region","Total Revenue"]
    with open(file_path2,mode="w",newline="") as file:
        writer=csv.writer(file)
        writer.writerow(headers)
    print("Sales Summary created.")
    
def update_ss():
    with open(file_path1,mode="r") as file1:
        reader=csv.DictReader(file1)
        Product=[]
        Region=[]
        Sale=[]
        Price=[]
        for row in reader:
            Product.append(row["Product"])
            Region.append(row["Region"])
            Sale.append(row["Sales"])
            Price.append(row["Price"])
        with open(file_path2,mode="a",newline="") as file2:
            writer=csv.writer(file2)
            for i in range(len(Product)):
                writer.writerow([Product[i],Region[i],float(Sale[i])*float(Price[i])])
            print("Sales Summary updated.")
            
def calculation():
    with open(file_path2,mode="r")as file:
        reader=csv.DictReader(file)
        total=0
        n=0
        highest=0
        sales_data=[]
        for row in reader:
            total+=float(row["Total Revenue"])
            n+=1
            sales_data.append(row)
            if float(row["Total Revenue"])>=highest:
                highest=float(row["Total Revenue"])
        print(f"The average mean is {total/n:.2f}")
        print(f"The highest revenue= {highest} ")
        
        
    revenue=np.array([float(row["Total Revenue"]) for row in sales_data]) 
    average_revenue=np.mean(revenue)
    print(f"The average mean is {average_revenue}")
    product_revenue_map={row["Product"]:row["Total Revenue"] for row in sales_data}
    product_with_highest_revenue=max(product_revenue_map,key=product_revenue_map.get)
    print(f"The highest revenue= {product_with_highest_revenue} ")
    region_revenue_map={}
    for row in sales_data:
        region=row["Region"]
        region_revenue_map[region]=region_revenue_map.get(region,0)+float(row["Total Revenue"])
    print(f"The revenue by region is {region_revenue_map}")
    
        
        
create_sd()
add_sale("Bag","Kathmandu",5,1000)
add_sale("Pouch","Lalitpur",2,500)
add_sale("Pouch","Kathmandu",10,500)
generate_random_sales_data(10)
create_ss()
update_ss()
calculation()
    
    

Sales Data created.
Sale Record added
Sale Record added
Sale Record added
Sale Record added
Sale Record added
Sale Record added
Sale Record added
Sale Record added
Sale Record added
Sale Record added
Sale Record added
Sale Record added
Sale Record added
Generated 10 random sales records.
Sales Summary created.
Sales Summary updated.
The average mean is 218070.09
The highest revenue= 840233.01 
The average mean is 218070.09230769234
The highest revenue= Headphones 


TypeError: unsupported operand type(s) for +: 'int' and 'str'