In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print("1D array")
print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np
ar=np.array([[1,2,3],[4,5,6]])
print("2D array")
print(ar)

2D array
[[1 2 3]
 [4 5 6]]


In [7]:
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(d)

0
1
2
3
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [9]:
print(c[0,1])
print(d[0,0,2])

2
3


In [4]:
import numpy as np
import random 

matrix= np.random.randint(1,21,(4,4))
print("Original Matrix")
print(matrix)

diagonal_sum=np.trace(matrix)
print(f"\n Sum of diagonal elements:{diagonal_sum}")

flipped_matrix=np.flip(matrix)
print("\n Flipped matrix:")
print(flipped_matrix)

positions=np.argwhere(matrix>15)
print("\n Positons of elements greater than 15:")
for pos in positions:
    print(f"Row {pos[0]+1},Column {pos[1]+1}")

Original Matrix
[[ 9  3  6 14]
 [20  9 14 13]
 [ 1 11 20  7]
 [12  6  9  9]]

 Sum of diagonal elements:47

 Flipped matrix:
[[ 9  9  6 12]
 [ 7 20 11  1]
 [13 14  9 20]
 [14  6  3  9]]

 Positons of elements greater than 15:
Row 2,Column 1
Row 3,Column 3


In [6]:
import csv

file_path="sales_tracker.csv"

def create_csv():
    headers=["Date","Product","Quantity","Price per Unit","Total"]
    with open(file_path,mode='w',newline="") as file:
        writer=csv.writer(file)
        writer.writerow(headers)
    print("Sales tracker created.")
    
def add_sale(date,product,quantity,price_per_unit):
    total=quantity*price_per_unit
    with open(file_path,mode="a",newline="") as file:
        writer=csv.writer(file)
        writer.writerow([date,product,quantity,price_per_unit,total])
    print("Sale record added.")
    
def calculate_total_sales():
    total_sales=0
    with open(file_path,mode="r") as file:
        reader=csv.DictReader(file)
        for row in reader:
            total_sales+=float(row["Total"])
    print(f"Total Sales: ${total_sales:.2f}")
    
create_csv()
add_sale("2025-01-06","Laptop",2,1200.50)
add_sale("2025-01-06","Mouse",5,25.99)
calculate_total_sales()

Sales tracker created.
Sale record added.
Sale record added.
Total Sales: $2530.95
